### ISSUE TITLE
DSDT patches

### ISSUE THREAD

**Issue by kyvaith** [rafaelmaeuer/Asus-UX32VD-Hackintosh#1]
Hi,

Can you provide a list of patches for your DSDT?

Thanks.

**Comment by rafaelmaeuer** [comment]
Hi, 
I am just using an already patched DSDT so I am sorry I cannot provide this. But have a look at [danieleds](https://github.com/danieleds/Asus-UX32VD-Hackintosh/tree/master/src/DSDT) repo, there you can find a good list to start with.

**Comment by kyvaith** [comment]
Thanks. May I ask where have you found the patched DSDT? The one in @danieleds repo od diferent.

**Comment by rafaelmaeuer** [comment]
puh im not sure if I can find the source again, has been some time ago, if I have some time I will have a look for it.

**Comment by kyvaith** [comment]
Great, thank you :)

**Comment by rafaelmaeuer** [comment]
Hey, 

you might have luck looking at these two links I found in my archive, there are some DSDTs provided:
https://www.insanelymac.com/forum/topic/281201-booting-mountain-lion-on-an-asus-ux32vd/
https://www.insanelymac.com/forum/topic/283038-asus-zenbook-prime-ux31a-db51-ultrabook-fixes-mods-tweaks-etc/
