### ISSUE TITLE
nv_disable=1

### ISSUE THREAD

**Issue by idoo** [rafaelmaeuer/Asus-UX32VD-Hackintosh#10]
Do we need that parameter during boot?

**Comment by rafaelmaeuer** [comment]
this is necessary to disable integrated nvidia chip from being initialized. Bringing the nvidia gpu to work is a project for itself, but as there is no nvidia webdriver support from Mojave onwards, I guess an unnecessary try without options for hardware acceleration.

**Comment by rafaelmaeuer** [comment]
I just checked my clover config and I don't have this bootflag enabled anymore so no we don't need it during boot.
