### ISSUE TITLE
Sleep on close doesn't work

### ISSUE THREAD

**Issue by idoo** [rafaelmaeuer/Asus-UX32VD-Hackintosh#11]
Any ideas how to fix sleep?

**Comment by rafaelmaeuer** [comment]
I cannot properly test this at the moment, as I am running Mojave on my test SSD connected via USB. After wakeup the system freezes. Need to test this from internal SSD.

**Comment by idoo** [comment]
it just waked up immediately, do you know a way how to debug it? maybe some kext prevent that process?

**Comment by idoo** [comment]
I replaced SMBIOS to mac 13,1 and sleep mode now works well, but USB after wake up doesn't work :(

**Comment by idoo** [comment]
looks like USB doesn't work even before sleep, so as I got USB preventing laptop to go to sleep

**Comment by idoo** [comment]
@rafaelmaeuer hey! looks like you updated you laptop?
did you fix sleep?

**Comment by rafaelmaeuer** [comment]
hey @idoo I only updated the readme, I will update the Machine probably in 2-3 weeks, if I have time I will have a look at the sleep issue then. Are you still using yours?

**Comment by idoo** [comment]
not really, it's more fun project — but I could help you to debug something if you need help :)

**Comment by idoo** [comment]
Looks like it works after update after 1 year 🎉
