### ISSUE TITLE
Enable TRIM on SSD

### ISSUE THREAD

**Issue by idoo** [rafaelmaeuer/Asus-UX32VD-Hackintosh#12]
Any ideas how to enable trim?

I know only https://cindori.org/trimenabler/ that tool, is it good?

also here is way with 
`sudo trimforce enable`

https://www.hackintosh.computer/190/enable-trim-on-macos/

**Comment by rafaelmaeuer** [comment]
Did not take care of this yet.

**Comment by idoo** [comment]
`sudo trimforce enable` helped me, so could you try it and add to readme?

**Comment by idoo** [comment]
there are patch as well in clover configurator

```
com.apple.iokit.IOAHCIBlockStorage

00415050 4C452053 534400
00000000 00000000 000000
```

but I didn't tested it since https://github.com/rafaelmaeuer/Asus-UX32VD-Hackintosh/issues/12#issuecomment-448552812 works well for me

**Comment by rafaelmaeuer** [comment]
added to readme, but its not clear if system benefits from enabling TRIM
