### ISSUE TITLE
Boot only with left USB

### ISSUE THREAD

**Issue by idoo** [rafaelmaeuer/Asus-UX32VD-Hackintosh#13]
For some reasons, I could boot install only from USB located on the left side. Is it cult of cargo or some particular reasons to work like that?

**Comment by rafaelmaeuer** [comment]
I didn't experienced this behavior yet. In my last install case the install usb was also plugged into the left side port, but I will try another one on next install.

**Comment by rafaelmaeuer** [comment]
Boot on right-sided usb-ports is working for me.

**Comment by rafaelmaeuer** [comment]
I found out that right USB next to AC is not working at all. Did you experience the same? USB next to HDMI is working for me also on boot...

**Comment by rafaelmaeuer** [comment]
I was able to fix it with a correct USB-Mapping
