### ISSUE TITLE
Mojave theme

### ISSUE THREAD

**Issue by idoo** [rafaelmaeuer/Asus-UX32VD-Hackintosh#14]
what do you think about that theme?
https://sourceforge.net/p/cloverefiboot/themes/ci/master/tree/themes/Mojave/

do we need to add it?

![image](https://user-images.githubusercontent.com/738921/50201429-1d54ee00-036b-11e9-95d7-9ceeca737d30.png)

**Comment by rafaelmaeuer** [comment]
it looks cool, yes we can add it to the clover themes

**Comment by rafaelmaeuer** [comment]
boot theme added
