### ISSUE TITLE
Screen resolution

### ISSUE THREAD

**Issue by idoo** [rafaelmaeuer/Asus-UX32VD-Hackintosh#17]
Are you able to check default screen resolution in windows/linux? looks like 1600x900 is not best (or at least not HiDPi) for that display and 1920x1080 too small for me

**Comment by rafaelmaeuer** [comment]
I use 1920x1080 in Windows which works fine for me

**Comment by idoo** [comment]
but you could see, that HDPI mode isn't enabled?

You could compare with HDPI mode by toggle it with [SwitchResX](http://www.madrau.com/)

**Comment by rafaelmaeuer** [comment]
I think the display resolution with 1920x1080 is too small to get a satisfying result with HiDPI-Mode.
