### ISSUE TITLE
DSDT generation

### ISSUE THREAD

**Issue by idoo** [rafaelmaeuer/Asus-UX32VD-Hackintosh#25]
I'm trying to generate my own DSDT what I did: 

1. extracted by pressing `F4` on the clover boot screen
2. installed https://bitbucket.org/RehabMan/acpica/downloads/
```
cd ~/Downloads
unzip iasl.zip
sudo cp iasl /usr/bin
```
3. copied my `DSDT` and `SSDT*.aml` files to dev folder and run
```
iasl -da -dl DSDT.aml SSDT*.aml
```

4. opened it with `MaciASL.app` and applied patches from https://github.com/danieleds/Asus-UX32VD-Hackintosh/tree/master/src/DSDT

5. pressed `saved as` and saved is as DSDT.aml
6. put to `clover/acpi/patched`, refreshed cache, selected it on boot

I have: `IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, now 0 sm 0x0`

What I did wrong?

**Comment by rafaelmaeuer** [comment]
DSDT generation is now included in the readme.
