### ISSUE TITLE
Consider about moving kext after install to /Library/Extensions

### ISSUE THREAD

**Issue by idoo** [rafaelmaeuer/Asus-UX32VD-Hackintosh#26]
As I got, the `/Library/Extensions` is a proper place for kext after installation (at least for wifi patches) what do you think if we'll move it to `/Library/Extensions` ?

https://github.com/RehabMan/OS-X-BrcmPatchRAM

```
BrcmFirmwareRepo.kext: Install to /System/Library/Extensions (/Library/Extensions on 10.11 and later). This kext is much more memory efficient than BrcmFirmwareData.kext and is the preferred configuration.
```

**Comment by rafaelmaeuer** [comment]
As custom kexts are not always update-safe when stored into /Library/Extensions/ I prefer to keep them injected with clover.

**Comment by idoo** [comment]
But I have the issue with Bluetooth sound with that configuration — it freezing. Could you test it on your laptop?

**Comment by rafaelmaeuer** [comment]
Is this still an issue? Please reopen if it persists.
