### ISSUE TITLE
Updates changelog

### ISSUE THREAD

**Issue by idoo** [rafaelmaeuer/Asus-UX32VD-Hackintosh#27]
updated to latest 10.14.3 (18D42) — can't see any new issues

Still not working for me:

- [ ] sleep
- [ ] random display glitches on boot

**Comment by idoo** [comment]
Updated to 10.14.3 (18D109)
Still working well

**Comment by rafaelmaeuer** [comment]
hey @idoo for what purpose do you intended this issue?
