### ISSUE TITLE
TODO: fix App Store access

### ISSUE THREAD

**Issue by idoo** [rafaelmaeuer/Asus-UX32VD-Hackintosh#28]
that fixed access to Mac App Store

https://www.youtube.com/watch?v=i-s_WLHX1JQ

**Comment by rafaelmaeuer** [comment]
what do you have for issues when using the app store?

**Comment by idoo** [comment]
I can't reproduce it anymore, but when I tried to open it — got error, that AppStore is not available

**Comment by rafaelmaeuer** [comment]
I never had problems with the app store
