### ISSUE TITLE
Step missed

### ISSUE THREAD

**Issue by idoo** [rafaelmaeuer/Asus-UX32VD-Hackintosh#3]
On Unibeast install step, I have to select UEFI or `compatibility`

What I should select?

**Comment by idoo** [comment]
@rafaelmaeuer btw, are you still using it?

**Comment by rafaelmaeuer** [comment]
Hi @idoo, yes I have it still in use, I was thinking about upgrading to Mojave, but need some time to do this. I don't remember exactly what to select, I guess you should go with UEFI, try it out. I will definitely know when doing the reinstall, but it will be around next year probably.

**Comment by idoo** [comment]
@rafaelmaeuer I believe it was UEFI because I've tried compatibility mode and it just not booting after patching, but can't confirm it because still can't get it loaded

**Comment by rafaelmaeuer** [comment]
In my test only with legacy option the drive was able to boot. But now for mojave unibeast is not longer necessary.
