### ISSUE TITLE
USB fix

### ISSUE THREAD

**Issue by idoo** [rafaelmaeuer/Asus-UX32VD-Hackintosh#30]
https://hackintosher.com/forums/thread/list-of-hackintosh-usb-port-limit-patches-10-14-updated.467/

**Comment by idoo** [comment]
works well now

**Comment by rafaelmaeuer** [comment]
For the rebuild with OpenCore an USB-Mapping was created with help of [corpnewt/USBMap](https://github.com/corpnewt/USBMap) following  Dortanias [USB Mapping-Guide](https://dortania.github.io/OpenCore-Post-Install/usb/intel-mapping/intel.html) which fixes all USB devices to work as expected.
