### ISSUE TITLE
Webacam is not recognized

### ISSUE THREAD

**Issue by almontic** [rafaelmaeuer/Asus-UX32VD-Hackintosh#32]
Hi Rafael, first of all thanks for your guide.
I've exactly your Notebook, with the same configuration.
Everything works fine under Calalina 10.15.4 (19E287) but WebCam.
Under System preferences it doesn't show up neither in "Camera" section or "USB" controllers.
I've tried almost everything on internet, have you got any suggestion? Does your webcam work?

**Comment by almontic** [comment]
@idoo Does your camera works? Thanks a lot

**Comment by idoo** [comment]
I'm using that laptop as fun project — so it still on Mojavie, and yes camera works well

**Comment by idoo** [comment]
@almontic I could confirm that with kext + config from repo camera stop working even on Mojave

**Comment by rafaelmaeuer** [comment]
I need to check, but at the moment I don't have the time...

**Comment by idoo** [comment]
let me know if you need some help to test something from my side :)

**Comment by almontic** [comment]
Thanks both for replies! I'm going to try to give you further info.
This is the situation of USB Controllers in System info:

![Screenshot 2020-04-23 at 16 25 39](https://user-images.githubusercontent.com/2485681/80110772-53b60500-857f-11ea-97e4-ade818d00d4c.png)

So far, the other USB works, even 3.0, but their is no trace of camera.
I tried with USBInjectAll + kext [patch for ports limit](https://www.tonymacx86.com/threads/macos-catalina-10-15-0-usb-port-limit-removal-patch.285098/) but nothing changed.
Even this fix [AnyISightCamera](https://www.insanelymac.com/forum/topic/238847-get-your-uvc-webcam-working-as-apple-isight/) didn't work.

Have you got any suggestion to debug the issue?

**Comment by rafaelmaeuer** [comment]
For me the internal camera works without problems. Please try to update with latest commit.
