### ISSUE TITLE
How can I fix my sleep without losing my Bluetooth?

### ISSUE THREAD

**Issue by darthdem** [rafaelmaeuer/Asus-UX32VD-Hackintosh#33]
there was always a standard card, I replaced it with Broadcom bcm9360hmb, the Bluetooth still didn't work, then I deleted the USB Port. kext and SSDT-UIAC, the Bluetooth worked perfectly, BUT the laptop stopped falling asleep

**Comment by rafaelmaeuer** [comment]
I am currently working on it -> hope for SSDT-GPRW.aml to solve this

**Comment by darthdem** [comment]
Well, thank you very much, I will wait for your solution to the problem

**Comment by rafaelmaeuer** [comment]
Hey although the patch didn't worked as expected, it solves the problem better than as expected 😄 
Check out the latest commit to get BT and sleep work together.

**Comment by darthdem** [comment]
Thank you very much, you solved the problem very quickly, now everything works perfectly!
