### ISSUE TITLE
verbose mode

### ISSUE THREAD

**Issue by darthdem** [rafaelmaeuer/Asus-UX32VD-Hackintosh#34]
In your configuration, you deleted "- v", but the detailed mode remains, is it an error or a function? :) 

As for the broken screen, is there no way to fix this error? (Yes, I know that closing the cover fixes this, I even found a faster way: hold the power off button for 1-2 seconds, the screen will turn off and then turn it on). 

I want to thank you for your work and for not forgetting about this laptop! Thanks to you, I have been using Mac OS as my main OS for 3 years now.

**Comment by rafaelmaeuer** [comment]
Without verbose boot (-v boot flag) you should see the Apple-logo at boot. If that is not the case, there might be something wrong. I didn't had the broken screen glitch for a while, but maybe I doesn't use the laptop frequently enough. Did you had it after setting iGPU in this [commit](https://github.com/rafaelmaeuer/Asus-UX32VD-Hackintosh/commit/542bc0ba15104b1a52633c29c68fae411667d795)?

**Comment by darthdem** [comment]
I use your EFI with your settings![Снимок экрана 2020-07-02 в 21 36 54](https://user-images.githubusercontent.com/67675256/86387650-ea542000-bcac-11ea-9df6-0bdea1c49a0b.png)
now I experiment a lot and often restart, I often break the screen. but okay, I'm used to it. But the download without the Apple logo surprised me

**Comment by darthdem** [comment]
resetting nvram helped me see the Apple logo, problem solved!:) 
but the broken screen I still get
