### ISSUE TITLE
"Install" option not showing up in Clover

### ISSUE THREAD

**Issue by Maghoumi** [rafaelmaeuer/Asus-UX32VD-Hackintosh#35]
First, thanks for putting this together and maintaining it! I'm very new to Hackintosh and I decided to give this a shot on my UX32VD as it's collecting dust these days! FYI, I have Ubuntu 20.04 running on it, but I wanna erase it completely and install Catalina.

I've been attempting this for the past 2 days without avail... I followed everything in your guide very carefully. I can boot up Clover from the USB, it even shows my Ubuntu UEFI boot entry. However, it's missing the `Install macOS Catalina` entry, as if it doesn't know where the installer is located. Searching online suggests maybe the HFS+ driver is not correctly loaded. But after following [this guide that you linked](https://hackintosher.com/forums/thread/guide-how-to-create-a-macos-catalina-10-15-0-usb-installer-drive-w-clover.2836/), I see `VfsHFS` driver on the Clover USB.

Also, the guide wasn't quite clear on whether I need 1) one single USB that has Clover on EFI and Catalina on the main partition, or 2) two USBs with Clover on one and the Catalina installer on the other. I tried both options to be safe, but I don't see an install entry under either one.

I also tried with Clover r5119 and r5120. Any help is greatly appreciated. Let me know if I can provide additional information.

**Comment by Maghoumi** [comment]
Nevermind... After trying for the 10th time, it magically worked and I was able to install everything and could use it for a few hours.

Unfortunately, something dumb happened earlier today. I went to the BIOS to disable CSM. After saving the settings and restarting, the laptop just completely died. It turns on, the fans spin and everything, but the ASUS logo doesn't come up (and there's also no output on the HDMI port either). The keyboard backlight comes on, and it just sits there. I think the BIOS might've been corrupted or something because even unplugging the battery and the RCT battery (to clear CMOS) didn't help either.

Very strange that this happened after saving my BIOS settings and exiting. Since searching online didn't yield any similar results, I just assume I'd need to desolder the BIOS chip and program in manually. 

Anyways... Closing this issue and thanks again for putting this together. It was great to get Mac running on this old laptop.

**Comment by rafaelmaeuer** [comment]
Hey and nice you got it working. Sad to hear about your BIOS problem. Did you tried pressing power button until it switches off?

**Comment by Maghoumi** [comment]
Yeah, I tried all sorts of things (unplugging the battery and the CMOS battery, etc.). To my surprise, this sudden corruption of the BIOS seems to be a common ASUS problem (e.g. https://forums.tomsguide.com/threads/laptop-black-screen-after-changing-settings-in-bios.402974/ ). 

I've seen many other forum posts about this too. I'm surprised that I didn't run into this issue in my 8 years of owning this laptop!!

Anyways... I just ordered an SPI programmer on Amazon. Will see if I can revive it.

**Comment by rafaelmaeuer** [comment]
Hmm strange - I wish good luck! Feel free to report the progress :)

**Comment by Maghoumi** [comment]
Just a quick update: my hunch was right! It really was a corrupted BIOS issue.

To avoid having to desolder the BIOS chip, I used [this programmer](https://www.amazon.com/gp/product/B07R5LPTYM/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1) that came with an 8-pin test clip. For future reference, the BIOS chip on the UX32VD is a [Macronix MX25L6445E](https://www.macronix.com/Lists/Datasheet/Attachments/7330/MX25L6445E,%203V,%2064Mb,%20v1.8.pdf) chip located on the bottom left of the RAM slot just above the battery.

Long story short, I read the BIOS data, dumped it into a file, took the first 2 MB (preamble) and concatenated it with the v214 BIOS downloaded from the ASUS website. I then flashed it and turned the laptop on, and to my amusement it booted right up!!

The strange thing though is that some of my BIOS options are now gone and I have some additional things instead :D For instance, all the CSM and secure boot options are gone. Instead, I have an option to sound a beep on successful POST. I tried to use v213 too, same deal.

Anyways, my Hackintosh is up and running again :)

**Comment by rafaelmaeuer** [comment]
Hey very nice to read this :)

Regarding your lost bios-settings: I don't remember of ever having seen a CSM setting in bios... But I do remember the sound option on successful post. I thought it would be nice to replace it with the typical Apple "BOOM" startsound. But I never put further effort in this.

Glad to hear the machine is running again :)

**Comment by Maghoumi** [comment]
Hmm... Interesting! I don't recall ever having that beep setting in my BIOS. This machine had 3 trips to the ASUS service center when it was about a year old. Maybe they flashed some custom BIOS or something...

Interesting idea about the Apple BOOM sound! I wonder if beep sound could be replaced by something else in the BIOS with the programmer. Will look into it at some point :)

Thanks again for your repo
