### ISSUE TITLE
Try RealtekCardReader(+Friend).kext

### ISSUE THREAD

**Issue by rafaelmaeuer** [rafaelmaeuer/Asus-UX32VD-Hackintosh#36]
Internal Card-Reader seem to work with [0xFireWolf/RealtekCardReader](https://github.com/0xFireWolf/RealtekCardReader) and [0xFireWolf/RealtekCardReaderFriend](https://github.com/0xFireWolf/RealtekCardReaderFriend):

```txt
Realtek Card Reader on UX32vd working with this new kexts:
- RealtekCardReader.kext
- RealtekCardReaderFriend.kext

I'm on Opencore 7.0.3 with Big Sur 11.6. Please test it!
```

**Comment by rafaelmaeuer** [comment]
Today I had the chance to give this a try, I updated all kexts and OpenCore to the latest version before testing. This is what system preferences shows in USB section about the device:

![Bildschirmfoto 2021-10-24 um 17 01 25](https://user-images.githubusercontent.com/6418459/138602426-4599b688-4185-4fcf-8095-53878e628d2c.png)

This controller with `product-id=0139` is listed under `Supported Devices` on [0xFireWolf/RealtekCardReader](https://github.com/0xFireWolf/RealtekCardReader#supported-devices):
<img width="737" alt="Bildschirmfoto 2021-10-24 um 17 56 26" src="https://user-images.githubusercontent.com/6418459/138602384-a654a3e9-c07f-406b-80a2-c7c2849fb840.png">


When adding both kexts (`RealtekCardReader` and `RealtekCardReaderFriend`) to OC, after reboot a CardReader is shown in system preferences, but only basic id-stuff not like the Info shown at the [driver friend repo](https://github.com/0xFireWolf/RealtekCardReaderFriend#introduction):

![Bildschirmfoto 2021-10-24 um 17 01 31](https://user-images.githubusercontent.com/6418459/138602486-e1877b1e-bf9e-40ac-81b6-aa5ad07b18f2.png)

It seems that the helper kexts does its job, but the driver itself is not working (also no effect when  putting sd-card in).

So I read `FAQs` and `known issues`, installed the `debug` version of the kext including the `debug enhancer`. The kext is loaded, here is the generated log: [rtsx.log](https://github.com/rafaelmaeuer/Asus-UX32VD-Hackintosh/files/7405843/rtsx.log)

<img width="1059" alt="Bildschirmfoto 2021-10-24 um 18 10 21" src="https://user-images.githubusercontent.com/6418459/138602658-d0fc5551-3f6a-43da-b6b8-9feb39940457.png">

It seems to successfully start the controller, but then hanging in some loop or so... any help is appreciated!

**Comment by juliovalco** [comment]
Excellent!

**Comment by rafaelmaeuer** [comment]
It works, but mounting a card was prevented by bitdefender-shield. So be aware to check your antivirus if you have the same issue.
