### ISSUE TITLE
Install clover after instalation

### ISSUE THREAD

**Issue by idoo** [rafaelmaeuer/Asus-UX32VD-Hackintosh#7]
Currently, I have an issue with `Install Clover in EFI partition of OS X HDD`

I booted to Mac, installed clover to root device, but it still didn't get a boot, any ideas how to fix?

**Comment by idoo** [comment]
https://www.tonymacx86.com/threads/solved-uefi-clover-boot-option-gone-after-bios-update.211715/#post-1409404

that fixed booting without USB, do we need to add it to docs?
`bcfg boot dump` =>

the latest was 01, so

`bcfg boot add 01 FS2:\EFI\CLOVER\CLOVERX64.EFI CloverUEFI`

**Comment by rafaelmaeuer** [comment]
I forgot to write about this, yes we should add it to the docs. I added the clover boot entry directly in BIOS. Maybe we should add both solutions.
