### ISSUE TITLE
Multitasking touchpad

### ISSUE THREAD

**Issue by idoo** [rafaelmaeuer/Asus-UX32VD-Hackintosh#8]
as I can see it shoul works by default with ApplePS2SmartTouchPad
```
<key>4FingerSwipeLeftAction</key>
<integer>6</integer>
<key>4FingerSwipeRightAction</key>
<integer>7</integer>
```

Is there option to get multitasking on the touchpad?

**Comment by rafaelmaeuer** [comment]
Multitasking is working (try 2-finger right-click or scroll in browser) or 4-finger-stretch/ or -join. But they are not correctly mapped to the native os x gestures. Read more here about ApplePS2SmartTouchPad.kext here: https://osxlatitude.com/forums/topic/1948-elan-focaltech-and-synaptics-smart-touchpad-driver-mac-os-x/

**Comment by rafaelmaeuer** [comment]
Nevertheless I never was really happy with the driver, as it will not feel as fluent as on Windows or a real mac touchpad.

**Comment by idoo** [comment]
so, there is no way to map it correctly?

**Comment by rafaelmaeuer** [comment]
I don't know check it out :D

**Comment by idoo** [comment]
as I can see there is `Fixed a bug with Karabiner app to allow mapping` in changelog

but at the same moment during four fingers swipe — it just randomly generates something with cmd, back etc keys

**Comment by idoo** [comment]
did you try https://bitbucket.org/RehabMan/os-x-voodoo-ps2-controller/downloads/ ?
I tried, but looks it's not used by my system

looks like just put to `efi\...\others` not enough, there are some cache I guess

**Comment by idoo** [comment]
```
Four Fingers:

Swipe Left: Hide/show Dock
Swipe Right: Shows Properties/info for the selected file/folder
```
it's what you mean?

I modified existing kext and now it works better with swipes :) will upload id once finish gestures modification

is there way to extract that fixes to https://github.com/rafaelmaeuer/Asus-UX32VD-Hackintosh/blob/master/EFI/CLOVER/config.plist

?

**Comment by rafaelmaeuer** [comment]
I used Karabiner to switch functionality of cmd with alt key, what is a more intuitive way of using, maybe there is another solution by patching the kext, but this was straight forward.

Do you mean adding the kext patches to clover config? I guess its possible with clover's kextToPatch-section, have a look at this: https://www.insanelymac.com/forum/topic/311512-clover-efi-bootloader-understanding-kextstopatch-how-to-guide/

**Comment by idoo** [comment]
For history codes fore remap:

https://osxlatitude.com/forums/topic/5966-details-about-the-smart-touchpad-driver-features/

@rafaelmaeuer you could remap without karabiners
https://osxlatitude.com/forums/topic/5969-details-about-the-enhanced-keyboard-for-smart-touchpad-driver/

btw, what is you karabiner config? did you moved fn to ctrl or it's not possible?

**Comment by rafaelmaeuer** [comment]
My karabiner config switches cmd with alt key. Have you found a satisfying solution by modifying the touchpad kext?

**Comment by BAndysc** [comment]
@idoo, @rafaelmaeuer For much much better (native macOS gestures) for Elan (according to my research, this is the touchpad in your laptop), check my version of kext: https://github.com/BAndysc/VoodooPS2/releases/

**Comment by rafaelmaeuer** [comment]
thanks for the hint, I will give it a try

**Comment by rafaelmaeuer** [comment]
@BAndysc I tried it today and it works like a charm. Thanks for suggesting, I added the kext to the repo.

**Comment by rafaelmaeuer** [comment]
@BAndysc in how far is your kext different from the original acidanthera/VoodoPS2 kext? 
Is it possible to use it with OpenCore? I cannot get touchpad or keyboard working with OC.

**Comment by BAndysc** [comment]
@rafaelmaeuer Hey, this is already merged into original Acidanthera VoodooPS2, so you should use official one now (especially that official has even few additional improvements to elan touchpad)

**Comment by rafaelmaeuer** [comment]
Nice thanks a lot for the quick response! My problem was adding the kext manually, so I forgot the kernel plugins :)
