### ISSUE TITLE
Brightness automatically goes down

### ISSUE THREAD

**Issue by idoo** [rafaelmaeuer/Asus-UX32VD-Hackintosh#9]
After install, I have an issue. During work, the brightness automatically goes down and I have to increase it manually. Any ideas what it can be related?

**Comment by rafaelmaeuer** [comment]
Yes this has to do with the ALS sensor which is controlled by the AsusNBFnKeys.kext. I disabled it as it was annoying, read here about configuration: https://osxlatitude.com/forums/topic/1968-fn-hotkey-and-als-sensor-driver-for-asus-notebooks/

**Comment by rafaelmaeuer** [comment]
You also can disable fine-adjustment of brightness there, which I found annoying too :D

**Comment by idoo** [comment]
as I get, there is no way to disable them ob boot step?

**Comment by idoo** [comment]
Looks I disable it by modifying kext, but probably better to debug and modify values of light sensor to correct one

**Comment by rafaelmaeuer** [comment]
Please check if problem persists with AsusSMC.kext
